############################################### CHANGE HERE ####################################################################
policy_path: "ckpts/loco.onnx"
use_gait: True
gait_parameters:
  frequencies: 1.5
  phase_offset: 0.5
  stance_ratio: 0.6
  kappa_gait_probs: 0.05
  desired_stance_width: 0.25
  desired_swing_height: 0.07

control_dt: 0.02
control_decimation: 4
################################################################################################################################


num_obs: 47
num_dof: 12
num_actions: 12
dof_idx: [ # change with num_dof
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
]
action_idx: [ # change with num_actions
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
]

kps: [ # change with urdf
  100, 100, 100, 150, 40, 40,   # left leg
  100, 100, 100, 150, 40, 40,   # right leg
  300, 300, 300,                # waist
  100, 100, 50, 50, 20, 20, 20, # left arm
  100, 100, 50, 50, 20, 20, 20  # right arm
]
kds: [ # change with urdf
  2, 2, 2, 4, 2, 2,     # left leg
  2, 2, 2, 4, 2, 2,     # right leg
  3, 3, 3,              # waist
  2, 2, 2, 2, 1, 1, 1,  # left arm
  2, 2, 2, 2, 1, 1, 1   # right arm
]

default_angles: [ # change with urdf
  -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,       # left leg
  -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,       # right leg
  0.0,  0.0, 0.0,                       # waist
  0.0,  0.0, 0.0, 0.0, 0.0,  0.0, 0.0,  # left arm
  0.0,  0.0, 0.0, 0.0, 0.0,  0.0, 0.0   # right arm
]
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
max_cmd: [0.3, 0.3, 0.3]
cmd_clip: [0.1, 0.1, 0.1]
cmd_debug: [0., 0., 0.]

clip_observations: 100.
clip_actions: 100.

transition_time: 50
